<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="deleteme" Id="{07419c8f-447f-4df7-834d-203d44a00868}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK deleteme
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="deleteme">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>